- hosts: testv
  sudo: yes
  tasks:
    - name: "update"
      yum: name=* state=latest
  
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: "epel"
      yum:
        name: epel-release
        state: latest
    - name: "pip install"
      yum:
        name: python-pip
        state: latest
    - name: "pip compose"
      pip: name=docker-compose state=present
    - name: "pip upgrade"
      yum: name=python* state=latest 
    - name: "install wget"
      yum: 
        name: wget 
        state: latest
    - name: "git"
      yum: 
        name: git
        state: latest
    - name: "Git"
    git:
      repo: ssh://my_rep@bitbucket.org/my_rep/my_rep.git
      accept_hostkey: yes
      key_file: /root/.ssh/id_rsa
      dest: /root/rvchub
      version: master
      clone: yes
    become: yes
    - name: "git pull"
      shell: git clone git@bitbucket.org:my_rep/my_rep.git
    - name: "docker-compose up"
      shell: cd /home/my_dir && docker-compose up -d
     - name: "docker-compose up"
      
