- hosts: aster
  sudo: yes
  tasks:
  - name: "remove release"
    yum:
      name: zabbix-release
      state: removed
  - name: "remove agent"
    yum:
      name: zabbix-agent
      state: removed
  - name: "repo"
    yum:
      name: https://repo.zabbix.com/zabbix/3.4/rhel/6/x86_64/zabbix-release-3.4-1.el6.noarch.rpm
      state: installed
  - name: "zabbix-install"
    yum:
      name: https://repo.zabbix.com/zabbix/3.4/rhel/6/x86_64/zabbix-agent-3.4.0-1.el6.x86_64.rpm
      state: installed
  - name: "conf agent"
    shell: var1=$(hostname) ; sed -e "s/Zabbix server/$var1/g" -e 's/127.0.0.1/yuor_ip/g' /etc/zabbix/zabbix_agentd.conf
  - name: "start zabbix"
    service:
      name: zabbix-agent
      state: started
